### PR TITLE
forsen quiz

### PR DESCRIPTION
**Pull request by Shagon94**
Hey Nymn, I've gone ahead and fixed your quiz just now, you still need to figure style the divs and whatnot but its working now :)

### CODE REVIEW

**Comment by ledroyy** [comment]
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠛⠉⠁⠄⢀⣤⣶⣶⣶⣶⣶⣤⣄⠄⠈⢿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠋⠄⠄⠄⠄⠄⢾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣆⣼⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⠋⠄⠄⠄⠄⠄⢀⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⢃⡀⠂⠄⠄⠄⠄⢿⣿⣿⣿⣿⣿⣶⡶⠤⣬⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⠁⠄⠄⠄⠄⠄⠄⠄⢸⣿⣿⣿⣿⣶⣾⣏⣀⣿⣿⣿⢳⣤⣜⣿
⣿⣿⣿⣿⣿⣿⠄⠄⠄⠄⠄⠄⠄⠄⢸⣿⣿⣿⣿⣿⣷⣾⣿⣿⣿⣿⣿⣁⣸⣿
⣿⣿⣿⣿⣿⣿⡀⠄⠄⠄⠄⠄⠄⠄⢸⣿⣿⣿⣿⣿⣿⣿⠿⠾⠯⣭⣿⣷⣿⣿
⣿⣿⣿⣿⣿⡿⠃⠄⠄⠄⠄⠄⠄⠄⢈⣿⣿⣿⣿⣿⠋⠄⠄⠄⠄⠈⠄⠙⡿⣿
⣿⣿⣿⣿⡉⠄⠄⠄⠄⠄⠄⠄⠄⠄⠘⢿⣿⣽⣿⠄⠐⢦⣴⣶⢚⠋⠄⠄⣁⣿
⣿⣿⣿⣿⣷⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠉⠁⠉⠁⠄⠄⠄⠸⢷⣾⡄⠄⠄⢸⣿
⣿⣿⠿⠛⠋⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⢿⠇⠄⠄⢸⣿
⠋⠁⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⢀⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⢸⣿
⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠘⣧⣄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⣸⣿

**Comment by Nymnion** [comment]
can you update it to match current version

**Comment by Shagon94** [comment]
Yeah, I'm in chat, im resolving the conflicts now

**Comment by Shagon94** [comment]
Mr Nymn, the conflicts are resolved, you are pushing way too frequently and we gotta fix the conflicts, hence why you are seeing some files changed.

**Pull request closed without merging**
