### PR TITLE
Added a clips page 

### PR DESCRIPTION
**Pull request by jp1995**
Added a clips page  that lists the most popular forsen clips from the past month (timeframe could be changed)

image)

Also the shared elements of every page should really be templated so people wouldn't have to change every page to add an additional item to the navbar, for example. LULE whatever

### CODE REVIEW

**Comment by demibit** [comment]
If there is a clips page it might also make sense to move the ones from Home to here? What do you think

**Comment by gempir** [comment]
Too much to review 
image

**Comment by jp1995** [comment]
It's poo right now but I'll make it better later tonight and add an expanding overlay and an actual embed

**Comment by jp1995** [comment]
The clips from home are like meme clips though they kinda fit there more. This is all dynamically pulled (from LSF lule) @demibit

**Comment by demibit** [comment]
Aaah, makes sense @jp1995 LGTM Clueless

**Comment by jp1995** [comment]
Looks fine, seems to work well, tested it on the fork's github pages. Sorry about the CNAME commits, it did it automatically when I was testing the site. I reverted them all.

image

Now, I don't know what to do with that failing check. It's making me think I've done something terribly wrong but it's 5am and I don't want to think about it so I'm going to bed.

**Comment by demibit** [comment]
@jp1995 looks to me like `clips.html` and `js/clips.js` will need a newline at the end of the file and it should be fine

**Comment by jp1995** [comment]
idk kev. I'm pretty sure "Process completed with exit code 1." is normal and shouldn't produce an error

https://stackoverflow.com/questions/66626814/github-action-error-process-completed-with-exit-code-1

https://stackoverflow.com/questions/67113188/git-diff-returns-error-process-completed-with-exit-code-1-github-actions

**Comment by jp1995** [comment]
Amazin

**Pull request merged**
